# syntax=docker/dockerfile:experimental
FROM maven:3-eclipse-temurin-17 AS build
RUN mkdir -p /opt/app/src
COPY src /opt/app/src
COPY pom.xml /opt/app
RUN --mount=type=cache,target=/root/.m2 mvn -f /opt/app/pom.xml clean package
WORKDIR /opt/app
RUN java -Djarmode=layertools -jar /opt/app/target/demo-0.0.1-SNAPSHOT.jar extract

FROM eclipse-temurin:17
RUN mkdir /opt/app
WORKDIR /opt/app
#COPY --from=build /opt/app/target/demo-0.0.1-SNAPSHOT.jar /opt/app/app.jar
COPY --from=build /opt/app/dependencies/ ./
COPY --from=build /opt/app/spring-boot-loader/ ./
COPY --from=build /opt/app/snapshot-dependencies/ ./
COPY --from=build /opt/app/application/ ./
CMD ["java", "-jar", "/opt/app/app.jar"]